version: "3.9"
services:
  pantry-tracker-db:
    image: postgres
    restart: always
    container_name: pantry-tracker-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: